
# team01-be values
template:
  nameOverride: "team01-be"
  fullnameOverride: "team01-be"

  strategy:
    type: Recreate

  image:
    repository:  $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/team01-be-production-repo
    pullPolicy: Always
    tag: "production"

  prometheus:
    enabled: true
    scrape: "true"
    path: "/actuator/prometheus"
    port: "8080"

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

  serviceAccountName: "team01-be"

  env: {}
