# 수정된 values.yaml
nameOverride: "team01-be"
fullnameOverride: "team01-be"

strategy:
  type: Recreate

image:
  repository: 809691348554.dkr.ecr.ap-northeast-2.amazonaws.com/team01-be-production-repo
  pullPolicy: Always
  tag: "sha-66ae0b7"

prometheus:
  enabled: true
  scrape: "true"
  path: "/actuator/prometheus"
  port: "8080"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

service:
  port: 8080
  
serviceAccount:
  create: true
  name: team01-be
ingress:
  enabled: false
serviceAccountName: "team01-be"

env: {}
