replicaCount: 1

image:
  repository: 809691348554.dkr.ecr.ap-northeast-2.amazonaws.com/team02-be-production-repo
  pullPolicy: Always
  tag: "sha-d795b10" 

service:
  type: ClusterIP
  port: 8080

imagePullSecrets:
  - name: image-pull-secret

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false

serviceAccount:
  create: true
  name: team02-be

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

secret:
  name: team02-config

volumeMounts:
  - name: config-volume
    mountPath: /vault/secrets/application.yml
    subPath: application.yml
    readOnly: true

volumes:
  - name: config-volume
    secret:
      secretName: team02-config

podAnnotations: {}
podLabels: {}
nodeSelector: {}
affinity: {}
tolerations: {}
securityContext: {}
