replicaCount: 1

serviceAccount:
  create: true
  name: team02-be

image:
  repository: 809691348554.dkr.ecr.ap-northeast-2.amazonaws.com/team02-be-production-repo
  tag: sha-abcdef1 
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regcred

containerPort: 8080

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
