replicaCount: 1

serviceAccountName: team02-be

image:
  repository: 809691348554.dkr.ecr.ap-northeast-2.amazonaws.com/team02-be-production-repo
  tag: sha-abcdef1  # 실제 SHA로 교체됨
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  port: 80
