apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team02-be
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TP1-OuterMSA/msa-infra-main.git
    targetRevision: main
    path: charts/services/team02-be
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: msa-back
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
