template:
  fullname: init-ingress
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "300"
  hosts:
    - host: "k8s-node-02-404414479.ap-northeast-2.elb.amazonaws.com"
      paths:
        - path: /team2
          pathType: Prefix
          serviceName: team02-fe
          servicePort: 80
        - path: /team3
          pathType: Prefix
          serviceName: team03-fe
          servicePort: 80
        - path: /
          pathType: Prefix
          serviceName: init-page
          servicePort: 80


