replicaCount: 1

image:
  repository: 809691348554.dkr.ecr.ap-northeast-2.amazonaws.com/team03-be-production-repo
  pullPolicy: Always
  tag: "sha-abc1234" # CD 파이프라인에서 자동 변경됨

service:
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false

secret:
  name: team03-config # 쿠버 시크릿 이름

volumeMounts:
  - name: config-volume
    mountPath: /vault/secrets/application.yml
    subPath: application.yml
    readOnly: true

volumes:
  - name: config-volume
    secret:
      secretName: team03-config

podAnnotations: {}
podLabels: {}
imagePullSecrets: []
nodeSelector: {}
affinity: {}
tolerations: {}
securityContext: {}
