replicaCount: 1

image:
  repository: 809691348554.dkr.ecr.ap-northeast-2.amazonaws.com/team04-be-production-repo
  pullPolicy: Always
  tag: "sha-7fa0f89" 

service:
  type: ClusterIP
  port: 8080

imagePullSecrets:
  - name: image-pull-secret


resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
  
serviceAccount:
  create: true
  name: team04-be

ingress:
  enabled: false  # 필요시 true
  annotations: {}
  hosts: []
  tls: []


secret:
  name: team04-config # 쿠버 시크릿 이름

volumeMounts:
  - name: config-volume
    mountPath: /vault/secrets/application.yml
    subPath: application.yml
    readOnly: true

volumes:
  - name: config-volume
    secret:
      secretName: team04-config

podAnnotations: {}
podLabels: {}
nodeSelector: {}
affinity: {}
tolerations: {}
securityContext: {}
