nameOverride: "team04-be"
fullnameOverride: "team04-be"

strategy:
  type: Recreate

image:
  repository: 809691348554.dkr.ecr.ap-northeast-2.amazonaws.com/team02-be-production-repo
  pullPolicy: Always
  tag: "sha-66ae0b7"

prometheus:
  enabled: true
  scrape: "true"
  path: "/actuator/prometheus"
  port: "8080"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

imagePullSecrets:
  - name: ecr-pull-secret


serviceAccount:
  create: true
  name: team04-be
ingress:
  enabled: false
service:
  port: 8080
  type: ClusterIP

serviceAccountName: "team04-be"

env: {}
