# Default values for microservice template
replicaCount: 2

image:
  repository: null
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ""

# Vault 설정
vault:
  enabled: true
  environment: "dev"

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

# Vault 비활성화 시 사용할 환경 변수 (개발 전용)
env: {}

livenessProbe:
  enabled: true
  path: /actuator/health
  initialDelaySeconds: 60
  periodSeconds: 10

readinessProbe:
  enabled: true
  path: /actuator/health
  initialDelaySeconds: 30
  periodSeconds: 10
